# Generated by Django 5.2.6 on 2025-09-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroDeAprendizado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningrecord',
            name='knowledge_type',
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='learning_type',
            field=models.CharField(choices=[('Course', 'Course'), ('Book', 'Book'), ('Article', 'Article'), ('Video', 'Video'), ('Podcast', 'Podcast'), ('Workshop', 'Workshop'), ('Webinar', 'Webinar')], default='Article', max_length=50),
        ),
    ]
