# Generated by Django 5.2.6 on 2025-10-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroDeAprendizado', '0002_remove_learningrecord_knowledge_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('learning_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='centroDeAprendizado.learningrecord')),
            ],
        ),
    ]
