# Generated by Django 5.2.6 on 2025-10-22 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroDeAprendizado', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
